### ISSUE TITLE
README.md link to NHS Digital Develop hub broken

### ISSUE THREAD

**Issue by grahamd99** [NHSDigital/immunisation-history-api#116]
**Describe the bug**
README.md 

"Consumers of the API will find developer documentation on the NHS Digital Developer Hub." is broken.

Specifically https://developer.digital.nhs.uk/. Should instead be https://digital.nhs.uk/developer ?

**To Reproduce**
Just look at the README.md file, e.g. https://github.com/NHSDigital/immunisation-history-api/blob/master/README.md

**Expected behavior**
Link should work

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by michaelthemoon** [comment]
Hi Graham. We have moved this into Jira (DALA-898) and a fix branch is open. 

Thanks for raising this with us.
